### ISSUE TITLE
Run as Ip, default set to current IP?

### ISSUE THREAD

**Issue by DonBananos** [HateMonger/CryptChatServer#1]
When selecting 'Run as IP', shouldn't we set it to, by default, have the machines current IP address?

**Comment by HateMonger** [comment]
Jo men det er meget nemmere bare at taste den ind.. Conputere i dag har jo 5+ netkort og endnu flere hvis du har installeret vmware eller lign.

**Comment by DonBananos** [comment]
True. Har vendt mig til at arbejde i web, hvor man kun har én IP. 
Men kan vi eventuelt lave et script der henter IP fra IP config?
Man vil vel altid have et decideret public IP? Altså en IP som er gældende når man bruget et netværk.

**Comment by HateMonger** [comment]
Jo men ip adressen skal jo kun tastes ind en gang..  Så jeg syntes det er lidt overkill at scripte den del. 

Jeg mener når serveren køre så køre den. Så det er kun hvis den crasher man skal taste den ind igen og starte serveren. I teorien behøver vi slet ikke gui - vi kan starte den som en service under windows.

Det er bare for at gøre det nemmere for os når man kommer til at køre serveren på laptops både hjemme og i skolen mm.

**Comment by HateMonger** [comment]
Ipconfig kan ikke se din eksterne ip,
Men den skal også køre på serverens interne ip og så skal porten mappes igennem firewallen...

**Comment by DonBananos** [comment]
Normalt set kender man ikke sin egen IP adresse, og ved at lave et lille script der henter denne så kan man gøre det lettere for slutbrugeren

**Comment by HateMonger** [comment]
Ok, hvis man har en server får den ikke sin ip adresse dynamisk den skal tastes statisk in i windows. For hvis routeren pludselig (grundet reboot/strøm mangel eller lign.) tildeler serveren en anden ip adresse så peger firewallens port mapping på en forkert ip. Derfor ved alle server admins hvad deres servere hedder ip mæssigt og hvad firewallen hedder på ydersiden. Selv i apache og windows' web servere skal du taste ip ind og det er et par af de mest brugte webservere derude.

Der er også mange servere som har flere netkort mm. Så det er helt klart den nemmeste måde at gøre det på.

Der er ikke noget værre en automatik som man ikke kan stole 100% på.
